### ISSUE TITLE
macos编译错误

### ISSUE THREAD

**Issue by wjx0912** [Reknij/Lola#1]
```
error[E0433]: failed to resolve: use of undeclared crate or module `winres`
 --> build.rs:4:23
  |
4 |         let mut res = winres::WindowsResource::new();
  |                       ^^^^^^ use of undeclared crate or module `winres`

```

希望解决。谢谢

**Comment by Reknij** [comment]
我本身只有window。没有mac os，无法尝试解决。不过看起来是找不到`winres`这个crate，请确保确保添加了`winres`，正常来说我设置了编译条件，只有window才通过那段代码，不知mac os是如何通过的？

如果还是无法解决或是嫌麻烦，最直接简单粗暴的方法是删了那段代码即可，那代码只是为window程序(.exe)添加了`需要以管理员身份运行`的条件罢了。
